whoami: api-store
output: grpc
level: trace
grpc:
  address: "127.0.0.1"
  port: 50052
log_fields:
  include_thread_id: true
  include_target: true
  include_file: true
  include_line: true
  include_timestamp: true
debug_mode:
  enabled: true
  test_interval_secs: 200
